### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by jantman** [jantman/machine-access-control#34]
* [x] post Oops/Unoops and Lock/Unlock to Admin and Oops channels
* [x] post ALL logs to Admin channel:
   * [x] RFID removed (session end)
   * [x] Unknown RFID inserted
   * [x] RFID inserted while oopsed
   * [x] RFID inserted while locked out
   * [x] authorized RFID inserted
   * [x] unauthorized RFID inserted
* [x] **DEFER to a future issue** make a post in a specific channel with the status of all machines, and edit/update it every time that changes (or edit/update a channel canvas with machine status?)
* [x] Slack app or slash command that allows members of a specific private channel to oops/unoops a machine, lock and unlock a machine, list all machines, show status of all machines
* [ ] **ENSURE** that this all still works in a sane timeframe when Internet access is disabled (or do I need to do something like [call_soon_threadsafe()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.call_soon_threadsafe) or [run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools) to ensure that the HTTP response doesn't block on logging to Slack?)

general idea of slack bot:

```
/mac help
    USAGE:
    /mac list - list machines
    /mac status - list all machines and show their current status
    /mac clear MACHINE-NAME - clear oops and/or lock-out from this machine
    /mac lockout MACHINE-NAME - lock-out this machine
```

**Comment by jantmanAtCox** [comment]
Possibilities:

1. Run the existing Flask app and a Slack websocket client in individual threads. The websocket client handles oops/lock/status/machine list requests by directly accessing the relevant data/objects from the Flask config, using thread-safe locks. Messages that are posted to Slack in response to Flask events (i.e. logs, status updates) are just sent from the Flask thread.
2. Expose all of the information needed by the Slack bot via HTTP API endpoints in the Flask app.
